export enum BackEndNotification {
    CREATE_BOOKING = 'BACKEND.CREATE_BOOKING',
    CREATE_BOOKING_FOR_STUDENT = 'BACKEND.CREATE_BOOKING_FOR_STUDENT',
    CREATE_BOOKING_FOR_TEACHER = 'BACKEND.CREATE_BOOKING_FOR_TEACHER',
    CREATE_BOOKING_FOR_ADMIN = 'BACKEND.CREATE_BOOKING_FOR_ADMIN',
    UPDATE_STATUS_BOOKING = 'BACKEND.UPDATE_STATUS_BOOKING',
    UPDATE_STATUS_BOOKING_TEACHER_CANCEL = 'BACKEND.UPDATE_STATUS_BOOKING_TEACHER_CANCEL',
    UPDATE_STATUS_BOOKING_TEACHER_ABSENT = 'BACKEND.UPDATE_STATUS_BOOKING_TEACHER_ABSENT',
    UPDATE_STATUS_BOOKING_STUDENT_CANCEL = 'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_CANCEL',
    UPDATE_STATUS_BOOKING_STUDENT_ABSENT = 'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_ABSENT',
    TEACHER_LATE_TO_CLASS = 'BACKEND.TEACHER_LATE_TO_CLASS',
    TEACHER_LATE_TO_CLASS_FOR_STUDENT = 'BACKEND.TEACHER_LATE_TO_CLASS_FOR_STUDENT',
    TEACHER_LATE_TO_CLASS_FOR_TEACHER = 'BACKEND.TEACHER_LATE_TO_CLASS_FOR_TEACHER',
    TEACHER_LATE_TO_CLASS_FOR_ADMIN = 'BACKEND.TEACHER_LATE_TO_CLASS_FOR_ADMIN',
    TEACHER_HAVE_MONTHLY_MEMOS_TO_COMMENT = 'BACKEND.TEACHER_HAVE_MONTHLY_MEMOS_TO_COMMENT',
    TEACHER_HAVE_LATE_MONTHLY_MEMOS = 'BACKEND.TEACHER_HAVE_LATE_MONTHLY_MEMOS',
    TEACHER_HAS_UPGRADE_REQUEST_FOR_ADMIN = 'BACKEND.TEACHER_HAS_UPGRADE_REQUEST_FOR_ADMIN',
    TEACHER_HAVE_NEW_COURSE_MEMO = 'BACKEND.TEACHER_HAVE_NEW_COURSE_MEMO',
    TEACHER_HAVE_LATE_COURSE_MEMO = 'BACKEND.TEACHER_HAVE_LATE_COURSE_MEMO',
    TEACHER_HAVE_NEW_REGULAR_CALENDAR = 'BACKEND.TEACHER_HAVE_NEW_REGULAR_CALENDAR',
    TEACHER_ABSENT_REGULAR_CALENDAR = 'BACKEND.TEACHER_ABSENT_REGULAR_CALENDAR',
    TEACHER_UPDATE_REGULAR_CALENDAR = 'BACKEND.TEACHER_UPDATE_REGULAR_CALENDAR',
    STUDENT_ORDER_NEARLY_OUT_OF_CLASS = 'BACKEND.STUDENT_ORDER_NEARLY_OUT_OF_CLASS',
    NEW_SALE_OFF = 'BACKEND.NEW_SALE_OFF',
    COMPLETED_CLASS_WITHOUT_RATING = 'BACKEND.COMPLETED_CLASS_WITHOUT_RATING',
    SUBSTITUTE_BOOKING_FOR_STUDENT = 'BACKEND.SUBSTITUTE_BOOKING_FOR_STUDENT',
    SUBSTITUTE_BOOKING_FOR_ADMIN = 'BACKEND.SUBSTITUTE_BOOKING_FOR_ADMIN',
    ALERT_ORDERED_PACKAGE_WILL_EXPIRE = 'BACKEND.ALERT_ORDERED_PACKAGE_WILL_EXPIRE',
    ALERT_OVER_ABSENT_COURSE = 'BACKEND.ALERT_OVER_ABSENT_COURSE',
    ALERT_DO_NOT_HOMEWORK = 'BACKEND.ALERT_DO_NOT_HOMEWORK',
    CHANGE_TEACHER_BY_CRONJOB = 'BACKEND.CHANGE_TEACHER_BY_CRONJOB',
    NEXT_COURSE = 'BACKEND.NEXT_COURSE',
    FINISH_CURRICULUM = 'BACKEND.FINISH_CURRICULUM',
    STUDENT_SUBMIT_IELTS_WRITING = 'BACKEND.STUDENT_SUBMIT_IELTS_WRITING',
    DUPLICATE_STUDENT_INFORMATION = 'BACKEND.DUPLICATE_STUDENT_INFORMATION',
    REMINE_DO_HOME_WORK = 'BACKEND.REMINE_DO_HOME_WORK',
    UPDATE_STATUS_BOOKING_STUDENT_CANCEL_FOR_STUDENT = 'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_CANCEL_FOR_STUDENT',
    UPDATE_STATUS_BOOKING_STUDENT_ABSENT_FOR_STUDENT = 'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_ABSENT_FOR_STUDENT',
    DAILY_BOOKING_REMINDER_FOR_STUDENT = 'BACKEND.DAILY_BOOKING_REMINDER_FOR_STUDENT',
    STA_BOOKING_REMINDER_FOR_STUDENT = 'BACKEND.STA_BOOKING_REMINDER_FOR_STUDENT',
    CHANGE_TEACHER_BY_CRONJOB_FOR_STUDENT = 'BACKEND.CHANGE_TEACHER_BY_CRONJOB_FOR_STUDENT',
    UPDATE_STATUS_SCHEDULE = 'BACKEND.UPDATE_STATUS_SCHEDULE',
    STA_BOOKING_REMINDER_FOR_ADMIN = 'BACKEND.STA_BOOKING_REMINDER_FOR_ADMIN',
    STUDENT_REQUEST_LEAVE = 'BACKEND.STUDENT_REQUEST_LEAVE',
    TEACHER_REQUEST_LEAVE_OVER_TIME_SLOT = 'BACKEND.TEACHER_REQUEST_LEAVE_OVER_TIME_SLOT',
    NOTIFICATION_VIA_STUDENT_EMAIL = 'BACKEND.NOTIFICATION_VIA_STUDENT_EMAIL',
}
export enum ZaloOANotification {
    ACTIVE_PACKAGE = 'ZALO.ACTIVE_PACKAGE',
    REMINE_CLASS = 'ZALO.REMINE_CLASS',
    TEACHER_REQUEST_ABSENT = 'ZALO.TEACHER_REQUEST_ABSENT',
    TEACHER_LATE_TO_CLASS = 'ZALO.TEACHER_LATE_TO_CLASS',
    HAPPY_BIRTHDAY = 'ZALO.HAPPY_BIRTHDAY',
    TEACHER_WRITE_MEMO = 'ZALO.TEACHER_WRITE_MEMO',
    REMINE_UPCOMING_TEST = 'ZALO.REMINE_UPCOMING_TEST',
    REMINE_TRIAL_CLASS = 'ZALO.REMINE_TRIAL_CLASS',
    REMINE_DO_HOME_WORK = 'ZALO.REMINE_DO_HOME_WORK',
    CHANGE_TEACHER = 'ZALO.CHANGE_TEACHER',
    INTERACTIVE_REMINDER = 'ZALO.INTERACTIVE_REMINDER',
    CALLBACK_INTERACTIVE_BUTTON_ACTIONS = 'ZALO.CALLBACK_INTERACTIVE_BUTTON_ACTIONS',
    PUBLISH_DILIGENCE_REPORT_FOR_STUDENT = 'ZALO.PUBLISH_DILIGENCE_REPORT_FOR_STUDENT',
    REMIND_TEACHER_EVALUATION_FOR_STUDENT = 'ZALO.REMIND_TEACHER_EVALUATION_FOR_STUDENT',
    REMIND_VIEW_MEMO_FOR_STUDENT = 'ZALO.REMIND_VIEW_MEMO_FOR_STUDENT'
}
export enum BackEndEvent {
    HAPPY_BIRTHDAY_EVENT = 'EVENT.HAPPY_BIRTHDAY_EVENT'
}

export enum EmailTemplate {
    LATE_TO_CLASS_FOR_STUDENT = 'EMAIL.LATE_TO_CLASS_FOR_STUDENT',
    LATE_TO_CLASS_FOR_TEACHER = 'EMAIL.LATE_TO_CLASS_FOR_TEACHER',
    LATE_TO_CLASS_FOR_ADMIN = 'EMAIL.LATE_TO_CLASS_FOR_ADMIN',
    NEW_BOOKING_FOR_STUDENT = 'EMAIL.NEW_BOOKING_FOR_STUDENT',
    NEW_BOOKING_FOR_TEACHER = 'EMAIL.NEW_BOOKING_FOR_TEACHER',
    UPDATE_STATUS_BOOKING_FOR_STUDENT = 'EMAIL.UPDATE_STATUS_BOOKING_FOR_STUDENT',
    UPDATE_STATUS_BOOKING_FOR_TEACHER = 'EMAIL.UPDATE_STATUS_BOOKING_FOR_TEACHER',
    VERIFY_EMAIL_FOR_STUDENT = 'EMAIL.VERIFY_EMAIL_FOR_STUDENT',
    VERIFY_EMAIL_FOR_TEACHER = 'EMAIL.VERIFY_EMAIL_FOR_TEACHER',
    LESSON_TEACHING_OVER_TIME = 'EMAIL.LESSON_TEACHING_OVER_TIME',
    TEACHER_REQUEST_REVIEW = 'EMAIL.TEACHER_REQUEST_REVIEW',
    FORGET_PASSWORD = 'EMAIL.FORGET_PASSWORD',
    NEW_ADMIN_ACCOUNT = 'EMAIL.NEW_ADMIN_ACCOUNT',
    NEW_REGULAR_CALENDAR_FOR_TEACHER = 'EMAIL.NEW_REGULAR_CALENDAR_FOR_TEACHER',
    STUDENT_ORDER_NEARLY_OUT_OF_CLASS = 'EMAIL.STUDENT_ORDER_NEARLY_OUT_OF_CLASS',
    ALERT_ORDERED_PACKAGE_WILL_EXPIRE = 'EMAIL.ALERT_ORDERED_PACKAGE_WILL_EXPIRE',
    ALERT_OVER_ABSENT_COURSE = 'EMAIL.ALERT_OVER_ABSENT_COURSE',
    ALERT_DO_NOT_HOMEWORK = 'EMAIL.ALERT_DO_NOT_HOMEWORK',
    DAILY_REPORT_ABSENT_CANCEL_TO_BOD = 'EMAIL.DAILY_REPORT_ABSENT_CANCEL_TO_BOD',
    DAILY_REPORT_MANAGEMENT = 'EMAIL.DAILY_REPORT_MANAGEMENT',
    REMINE_UPCOMING_TEST = 'EMAIL.REMINE_UPCOMING_TEST'
}

export const EMAIL_ADDRESS_EXCEPTION = ['hannahtoni09@gmail.com'];

export const NotificationZalo = 'BACKEND.ZALO';
export const NotificationZNS = 'BACKEND.ZNS';
export const NotificationTemplateSubject = 'BACKEND.TEMPLATE';
export const NotificationBroadcastSubject = 'BACKEND.ALL_USER';
export const PopUpEndBookingEvent = 'BACKEND.BOOKING_END_CLASS';

export enum ZNS_TEMPLATE {
    REMINE_TRIAL_CLASS = '249938',
    VERIFY_OTP = '283740'
}

export const NOTIFICATION_FILTERS = {
    TEACHER_ABSENT_REGULAR_CALENDAR: {
        LABEL: 'GV xin nghỉ Schedule',
        CODE: 'BACKEND.TEACHER_ABSENT_REGULAR_CALENDAR'
    },
    STUDENT_REQUEST_LEAVE: {
        LABEL: 'HV request leave',
        CODE: 'BACKEND.STUDENT_REQUEST_LEAVE'
    },
    SUBSTITUTE_BOOKING_FOR_ADMIN: {
        LABEL: 'Admin change GV',
        CODE: 'BACKEND.SUBSTITUTE_BOOKING_FOR_ADMIN'
    },
    TEACHER_LATE_TO_CLASS_FOR_ADMIN: {
        LABEL: 'GV vào muộn',
        CODE: 'BACKEND.TEACHER_LATE_TO_CLASS_FOR_ADMIN'
    },
    TEACHER_REQUEST_LEAVE_OVER_TIME_SLOT: {
        LABEL: 'Teacher Left',
        CODE: 'BACKEND.TEACHER_REQUEST_LEAVE_OVER_TIME_SLOT'
    },
    CREATE_BOOKING_FOR_ADMIN: {
        LABEL: 'New Booking',
        CODE: 'BACKEND.CREATE_BOOKING_FOR_ADMIN'
    },
    ALERT_ORDERED_PACKAGE_WILL_EXPIRE: {
        LABEL: 'HV sắp hết hạn',
        CODE: 'BACKEND.ALERT_ORDERED_PACKAGE_WILL_EXPIRE'
    },
    UPDATE_STATUS_BOOKING: {
        LABEL: 'Booking_other',
        CODE: 'BACKEND.UPDATE_STATUS_BOOKING'
    },
    UPDATE_STATUS_BOOKING_TEACHER_CANCEL: {
        LABEL: 'Booking_Cancel by teacher',
        CODE: 'BACKEND.UPDATE_STATUS_BOOKING_TEACHER_CANCEL'
    },
    UPDATE_STATUS_BOOKING_TEACHER_ABSENT: {
        LABEL: 'Booking_Teacher absent',
        CODE: 'BACKEND.UPDATE_STATUS_BOOKING_TEACHER_ABSENT'
    },
    UPDATE_STATUS_BOOKING_STUDENT_CANCEL: {
        LABEL: 'Booking_Cancel by student',
        CODE: 'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_CANCEL'
    },
    UPDATE_STATUS_BOOKING_STUDENT_ABSENT: {
        LABEL: 'Booking_Student Absent',
        CODE: 'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_ABSENT'
    },
    CHANGE_TEACHER_BY_CRONJOB: {
        LABEL: 'Hệ thống thay thế GV',
        CODE: 'BACKEND.CHANGE_TEACHER_BY_CRONJOB'
    },
    NEXT_COURSE: {
        LABEL: 'Next course',
        CODE: 'BACKEND.NEXT_COURSE'
    },
    FINISH_CURRICULUM: {
        LABEL: 'Finish curriculum',
        CODE: 'BACKEND.FINISH_CURRICULUM'
    },
    STUDENT_SUBMIT_IELTS_WRITING: {
        LABEL: 'HV nộp bài Ielts writing',
        CODE: 'BACKEND.STUDENT_SUBMIT_IELTS_WRITING'
    },
    DUPLICATE_STUDENT_INFORMATION: {
        LABEL: 'HV tạo trùng thông tin',
        CODE: 'BACKEND.DUPLICATE_STUDENT_INFORMATION'
    },
    ALERT_DO_NOT_HOMEWORK: {
        LABEL: 'Homework',
        CODE: 'BACKEND.ALERT_DO_NOT_HOMEWORK'
    },
    UPDATE_STATUS_SCHEDULE: {
        LABEL: 'Schedule Expired/Finished',
        CODE: 'BACKEND.UPDATE_STATUS_SCHEDULE'
    },
    STA_BOOKING_REMINDER_FOR_ADMIN: {
        LABEL: 'STA Booking',
        CODE: 'BACKEND.STA_BOOKING_REMINDER_FOR_ADMIN'
    },
    NOTIFICATION_VIA_STUDENT_EMAIL: {
        LABEL: 'ON/OFF Email',
        CODE: 'BACKEND.NOTIFICATION_VIA_STUDENT_EMAIL'
    },
    OTHER: {
        LABEL: 'Other',
        CODE: 'OTHER'
    }
};

export const NOTIFICATION_STUDENT_FILTERS = {
    DAILY_BOOKING_REMINDER_FOR_STUDENT: {
        LABEL: 'notification_tab.daily_booking_reminder_for_student',
        CODE: 'BACKEND.DAILY_BOOKING_REMINDER_FOR_STUDENT'
    },
    STA_BOOKING_REMINDER_FOR_STUDENT: {
        LABEL: 'notification_tab.sta_booking_reminder_for_student',
        CODE: 'BACKEND.STA_BOOKING_REMINDER_FOR_STUDENT'
    },
    CREATE_BOOKING_FOR_STUDENT: {
        LABEL: 'notification_tab.create_booking_for_student',
        CODE: 'BACKEND.CREATE_BOOKING_FOR_STUDENT'
    },
    SUBSTITUTE_BOOKING_FOR_STUDENT: {
        LABEL: 'notification_tab.substitute_booking_for_student',
        CODE: 'BACKEND.SUBSTITUTE_BOOKING_FOR_STUDENT'
    },
    CHANGE_TEACHER_BY_CRONJOB_FOR_STUDENT: {
        LABEL: 'notification_tab.change_teacher_by_cronjob_for_student',
        CODE: 'BACKEND.CHANGE_TEACHER_BY_CRONJOB_FOR_STUDENT'
    },
    ALERT_ORDERED_PACKAGE_WILL_EXPIRE: {
        LABEL: 'notification_tab.alert_ordered_package_will_expire',
        CODE: 'BACKEND.ALERT_ORDERED_PACKAGE_WILL_EXPIRE'
    },
    UPDATE_STATUS_BOOKING_STUDENT_CANCEL_FOR_STUDENT: {
        LABEL: 'notification_tab.update_status_booking_student_cancel_for_student',
        CODE: 'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_CANCEL_FOR_STUDENT'
    },
    UPDATE_STATUS_BOOKING_STUDENT_ABSENT_FOR_STUDENT: {
        LABEL: 'notification_tab.update_status_booking_student_absent_for_student',
        CODE: 'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_ABSENT_FOR_STUDENT'
    },
    REMINE_DO_HOME_WORK: {
        LABEL: 'notification_tab.remine_do_home_work',
        CODE: 'BACKEND.REMINE_DO_HOME_WORK'
    },
    COMPLETED_CLASS_WITHOUT_RATING: {
        LABEL: 'notification_tab.completed_class_without_rating',
        CODE: 'BACKEND.COMPLETED_CLASS_WITHOUT_RATING'
    },
    STUDENT_ORDER_NEARLY_OUT_OF_CLASS: {
        LABEL: 'notification_tab.student_order_nearly_out_of_class',
        CODE: 'BACKEND.STUDENT_ORDER_NEARLY_OUT_OF_CLASS'
    }
    // ,
    // OTHER: {
    //     LABEL: 'notification_tab.other',
    //     CODE: 'OTHER'
    // }
};

export const ARRAY_NOTIFICATION_STUDENT_CODE = [
    'BACKEND.DAILY_BOOKING_REMINDER_FOR_STUDENT',
    'BACKEND.STA_BOOKING_REMINDER_FOR_STUDENT',
    'BACKEND.CREATE_BOOKING_FOR_STUDENT',
    'BACKEND.ALERT_ORDERED_PACKAGE_WILL_EXPIRE',
    'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_CANCEL_FOR_STUDENT',
    'BACKEND.UPDATE_STATUS_BOOKING_STUDENT_ABSENT_FOR_STUDENT',
    'BACKEND.REMINE_DO_HOME_WORK',
    'BACKEND.SUBSTITUTE_BOOKING_FOR_STUDENT',
    'BACKEND.COMPLETED_CLASS_WITHOUT_RATING',
    'BACKEND.STUDENT_ORDER_NEARLY_OUT_OF_CLASS',
    'BACKEND.CHANGE_TEACHER_BY_CRONJOB_FOR_STUDENT'
];

export const ZALO_CALLBACK_DATA_OF_BUTTON_INTERACTIVE =
    'callback_data_button_interactive_heKj54dI5KGfRrk5kF';

export const ZALO_OA_MESSAGE_TYPE = {
    TRANSACTION: 'transaction',
    CS: 'cs'
};
