export enum EnumPackageOrderType {
    STANDARD = 1,
    PREMIUM = 2,
    TRIAL = 3
}

export enum EnumAlertType {
    ATTENDANCE_BY_NOTIFICATION = 1,
    WILL_EXPIRED_BY_NOTIFICATION,
    DO_NOT_HOMEWORK_BY_NOTIFICATION,
    ATTENDANCE_BY_EMAIL,
    WILL_EXPIRED_BY_EMAIL,
    DO_NOT_HOMEWORK_BY_EMAIL
}
